* Cunla tunes
** Objectif
Recueil des airs joués avec Cunla. Mélodie uniquement (pas les accords,
pas les commentaires). Classement par ordre approximatif
d'apprentissage. Respecter l'ordre des suites.

** Reste à faire
*** Mise en page
- +laisser lilypond afficher le titre, le type de morceau et le compositeur => plus de titre au sens latex+
- +permettre d'avoir plusieurs morceaux par page => plus de saut de ligne automatique.+
- +augmenter l'espacement entre les morceaux+
- +ne pas couper un morceau entre plusieurs pages+
- +augmenter la longueur des portées+

*** Formattage
- titre avec des accents sur le i: voir si ça existe en UTF-8 (ex. brid
  harper's)
- formattage des titres: majsucules partout? partout sauf sur les
  articles? Partout => lourd. => sur les noms propres uniquement
  (sentence case). Mais des fois c'est joli en title case...

http://en.wikipedia.org/wiki/Title_case#Headings_and_publication_titles

*** Goodies
- index alphabétique des airs (en ne tenant pas compte du déterminant:
  "the", "a", ...
- index alphabétique des airs par type (reel, jig, ..., autre)
- discographie: auteur (alphabétique) => album (par année) => liste des
  airs + type et numéro de page
- statistiques (nombre d'airs, nombres d'airs par type, nombre d'airs
  par compositeur, ...)
- liste des airs qui ne sont pas dans une suite

*** Build system
- +extension d'un doc lilypond-book: .lytex+
- mettre tous les fichiers générés dans un seul répertoire "out"

*** Tunes
- ajouter les airs manquants
- +vérifier que chaque air a un type (reel, jig, ...)+

* Style
Un type de morceau (Reel, Jig) commence par une majuscule (champ
informatif R: en abc, champ meter en lilypond)

Format de la discographie: Auteur, "Titre de l'album", Année

Quand le compositeur n'est pas connu, il vaut "Trad." à condition que ce
status soit à peu près avéré.

* Notes sur LaTeX et lilypond-book
Pour définir la longueur de la portée: 
- redéfinir les marges à l'aide du paquet latex "geometry"
- regénérer tout le livre

Remarque: dans mon cas, l'option line-width de lilypond-book ne
fonctionne pas (avec et sans ragged-margin)

Pour avoir un espacement vertical minimal raisonnable entre deux
morceaux: commencer un nouveau paragraphe à chaque morceau avec
\paragraph{}.
