* Feuille de route TDD
+\emph{Come Upstairs with Me}~(slip jig),~p.\pageref{come_upstairs_with_me}+
+Classement alphabétique d'après le titre+
+Mise en retrait du déterminant ("The Yellow Tinker" => "Yellow Tinker, The")+
+Prise en compte dans le classement alphabétique+
+gen_index_of_tunes+
+Nouveaux déterminants: "les", "le"_+
+format_index_entry(): prévoir le cas où le type de morceau n'est pas défini (e.g. "the crying game")+
+saut de page entre l'index des airs et l'index des suites+
+Affichage de l'index des airs en colonne+
+Titre du songbook: 2005-2010+
+sortie "cunla-tunebook.pdf" (au lieu de cunla.pdf)+

- index des suites: 

  - +si les 3 airs ont le même type, écrire le type en premier (pas+
    +italique) puis les 3 airs sans le type. Par exemple: "Jigs: Father+
    +O'Flynn (p.12), Brid Harper's (p.12)"_+

  - +exception: si il n'y a qu'un air dans la suite+

  - +pouvoir donner un nom à une suite. e.g. "The Oran Set"_+

  - +si tous les airs de la suite ont le même type, notation: "The Oran+
    +Set (reels): tune A, tune B". Nom du set en italique.+

  - numéro de page entres parenthèses, avec le type d'air si celui-ci
    est présent.

- sections: pouvoir définir des sections "latex" dans
  "cunla-tunes.txt". Exemple: "Airs sans suite".

* Cunla tunes
** Objectif
Recueil des airs joués avec Cunla. Mélodie uniquement (pas les accords,
pas les commentaires). Classement par ordre approximatif
d'apprentissage. Respecter l'ordre des suites.

** Reste à faire
*** Mise en page
- +laisser lilypond afficher le titre, le type de morceau et le compositeur => plus de titre au sens latex+
- +permettre d'avoir plusieurs morceaux par page => plus de saut de ligne automatique.+
- +augmenter l'espacement entre les morceaux+
- +ne pas couper un morceau entre plusieurs pages+
- +augmenter la longueur des portées+

*** Formattage
- +titre avec des accents sur le i: voir si ça existe en UTF-8 (ex. brid harper's)+

*** Goodies
- index alphabétique des airs par type (reel, jig, ..., autre)
- discographie: auteur (alphabétique) => album (par année) => liste des
  airs + type et numéro de page
- statistiques (nombre d'airs, nombres d'airs par type, nombre d'airs
  par compositeur, ...)
- liste des airs qui ne sont pas dans une suite

**** Index des airs (toute catégorie confondue)
Format: nom[, déterminant] (type) page

Exemple:

	Yellow Wattle, The (Jig) p.37

Autres considérations:
- Le nom du morceau est en italique.
- Classement alphabétique des tunes
- Disposition en colonne?

Données en entrée: le dictionnaire des tunes:
- clé = label
- champ = dictionnaire: clé = titre 'title' |type = 'type'

*** Build system
- +extension d'un doc lilypond-book: .lytex+
- mettre tous les fichiers générés dans un seul répertoire "out"

*** Tunes
- ajouter les airs manquants
- +vérifier que chaque air a un type (reel, jig, ...)+
- trouver les noms manquants:
  the_rolling_waves_of_frehel
  reel_amixo

* Style
Un type de morceau (Reel, Jig) commence par une majuscule (champ
informatif R: en abc, champ meter en lilypond)

Format de la discographie: Auteur, "Titre de l'album", Année

Quand le compositeur n'est pas connu, il vaut "Trad." à condition que ce
status soit à peu près avéré.

Formattage des titres: "title case" avec des majuscules partout sauf sur
majsucules partout sauf sur les articles et les formes du verbe être
(majuscules partout = lourd; que sur les noms propres = un peu triste
IMO)
http://en.wikipedia.org/wiki/Title_case#Headings_and_publication_titles

L'index des airs est affiché sur 2 colonnes
(http://texblog.wordpress.com/2007/08/11/creating-two-columns-in-article-report-or-book/)
en ne tenant pas compte du déterminant: "the", "a", ...

* Notes sur LaTeX et lilypond-book
Pour définir la longueur de la portée: 
- redéfinir les marges à l'aide du paquet latex "geometry"
- regénérer tout le livre

Remarque: dans mon cas, l'option line-width de lilypond-book ne
fonctionne pas (avec et sans ragged-margin)

Pour avoir un espacement vertical minimal raisonnable entre deux
morceaux: commencer un nouveau paragraphe à chaque morceau avec
\paragraph{}.
